config/routes.rb
Rails.application.routes.draw do

  get 'email/index'

  resources :profiles
  resources :contacts
get 'inbox'=> 'well#inbox'
get 'trash/well' => "well#trash" ,as: :tash_well
get 'well/restore/:id' => 'well#restore' ,as:  :well_restore
delete'well/deleted/:id' => 'well#delete', as: :well_remove
get 'favorite/well'=>"well#favorite_message" ,as: :favorite_well
get 'favorite_update'=> "well#favorite_update",as: :favorite_update
get 'home/index' => 'home#index' 
get '/new/home' => 'home#new'
put 'home/update'=>'home#update'

  resources :inbox
  resources :home

resources :well
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

   root 'email#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!
  def index
    Setting.find_or_create_by(user_id:current_user.id) do |s|
      s.inboxlimit = 10
    end
   end 

     def update
   	inboxlimit = Setting.find_by(user_id: current_user.id)
   inboxlimit.update(setting_params)
    redirect_to  well_index_path
    end   
  private
   def setting_params
     params.require(:setting).permit(:inboxlimit)
end

end 

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= form_for :setting, url: home_update_path, method: :'PUT' do |f| %>
 <input name="_method" type="hidden" value="put" />
</div>
  <div class="field">
    <%= f.label :setting%><br/>
    <%= f.text_field :inboxlimit%>
  </div>
  <div class="actions">
    <%= f.submit"save"  %>
  </div>
<% end %>

app/views/home/new.html.erb
<script type="text/javascript">
$(document).ready(function() {

    // page is now ready, initialize the calendar...

    $('#calendar').fullCalendar({
        // put your options and callbacks here
    })

});
	
	
</script>
<div id='calendar'></div>