config/routes.rb
Rails.application.routes.draw do

  get 'email/index'

  resources :profiles
  resources :contacts
get 'inbox'=> 'well#inbox'
get 'trash/well' => "well#trash" ,as: :tash_well
get 'well/restore/:id' => 'well#restore' ,as:  :well_restore
delete'well/deleted/:id' => 'well#delete', as: :well_remove
get 'favorite/well'=>"well#favorite_message" ,as: :favorite_well
get 'favorite_update'=> "well#favorite_update",as: :favorite_update
get 'home/index' => 'home#index' 
get '/new/home' => 'home#new'
put 'home/update'=>'home#update'

  resources :inbox
  resources :home

resources :well
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

   root 'email#index'

end

app/controllers/well_controller.rb
class WellController < ApplicationController
before_action :authenticate_user!
  def index
    @inboxlimit = current_user.settings.pluck(:inboxlimit).first
    @messages = Message.where(user_id: current_user.id,status: nil).order(created_at: :DESC).paginate(page: params[:page], per_page: @inboxlimit)
  
     
  
    
    #  @messages = Message.where(user_id: current_user.id,status: nil).paginate(page: params[:page], per_page: 2)
  end
 

  def new
    @message = Message.new
  end
  def create
      @message = current_user.messages.new(message_params)

      if @message.save
        redirect_to  well_index_path
      else
         render "new"
       end
    end
    def inbox
      #@message = Message.where(to: current_user.id, status: nil)
       @inboxlimit = current_user.settings.pluck(:inboxlimit).first
     @messages = Message.where(to: current_user.id,status: nil).paginate(page: params[:page], per_page: @inboxlimit)
    
    end
  def show
     @message =Message.find(params[:id])
  end
  def destroy
   @message=Message.find(params[:id])
 
     @message.update(status:'deleted')
  
    redirect_to  root_path
  end
    def trash
		@message = Message.where(to: current_user.id, status: 'deleted')
		@message = Message.where(user_id: current_user.id, status:'deleted')
	end
		def remove
		@message = Message.find(params[:id])
		
		@message.destroy
		
		redirect_to messages_trash_path
		
	end

	def restore
		@message = Message.find(params[:id])
		
		@message.update(status: nil)
		
		redirect_to root_path
	end
  def favorite_message
     @message = Message.all.where(to: current_user.email,favorite: 'true')
  end
  
  def favorite_update
         @message = Message.find(params[:id])
        @message.update_attributes(favorite: 'true')
        redirect_to root_path 
    end
private
   def message_params
     params.require(:message).permit(:user_id,:to,:image, :body,:status)
end





















 #  def index
 #  #	@body = Body.all

 #  end
 #  def new

 #  @body = Body.all
 #  end
 #  def create

 #      @body = Body.new(body_params)
	# 	if @body.save
	# 	redirect_to new_well_path	
 #        else
 #      redirect_to new_well_path
 #      end
 #    end
 #  def show
 #    @body=Body.find(params[:id])
 #  end
 
 #  private
 #  def body_params
 #    params.require(:body).permit(:to, :from, :image, :message)
 # end
end

app/helpers/well_helper.rb
module WellHelper
end

app/views/well/favorite_message.html.erb
<table>
  <tr>
    <!-- <th>TO</th> -->
    
    <th>MESSAGE</th>

    <th>FILE</th>
  </tr>
  
<% @message.each do |c| %>
<tr>
<td><%= c.to %></td>
<td><%= c.body %></td>
<td><%= c.image %></td><% end %>
</tr>
</table>
<%= link_to 'Back',  root_path %>

app/views/well/inbox.html.erb
<table>
  <tr>
      <%= link_to "settings", home_index_path %> 
     
    <th>FROM</th>
    
    <th>MESSAGE</th>

    <th>FILE</th>

  </tr>
  
<% @messages.each do |c| %>
<tr>

<td><%= c.user_id %></td>

<td><%= "#{c.body.first(10)}.........".to_s.html_safe %></td>
 
<td><%= link_to"Download file",c.image_url %></td>
<td><%= link_to"favorite", favorite_update_path(id:c) %></td>
<td><%= link_to"view",well_path(c) %></td>

<td><%= link_to "delete",well_path(c) , method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>
</tr>
</table>
<%= link_to 'Back',  root_path %> 

app/views/well/index.html.erb
<div class="row" style=" background: green">
  <table>
    <%= link_to "SETTINGS", home_index_path %> 
    <%= link_to 'Back', well_index_path %>
    <tr>
      <th>TO</th>
      <th>MESSAGE</th>
      <th>FILE</th>
    </tr>
    
    <% @messages.each do |c| %>

    <tr>
      <td><%= c.to %></td>
      <td><%# =c.body[0..10].html_safe %></td>
      <td><%= "#{c.body.first(10)}........".to_s.html_safe  %></td>
      <td><%= link_to"Download file",c.image_url %></td>
      <td><%= link_to"view",well_path(c) %></td>
      <td><%= link_to "delete",well_path(c) , method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  </table>
  <%= link_to 'Back',  root_path %> 
</div>

app/views/well/new.html.erb
<%= form_for :message, url: well_index_path do |f| %>
<div class="field">
  <%= f.label :to %><br />
  <%= f.select :to, User.all.collect{ |f| [f.email, f.id] if f.confirmed? } %>
  </div>
  <div class="field">
   <%= f.label :from%>
  <%= f.text_field :user_id ,value: current_user.email, readonly: :true%><br/>
    <%#= f.hidden_field :user_id , :value => current_user.email%>
  </div>
  <div class="field">
    <%= f.label :body%><br/>
    <%= f.cktext_area :body, :width => 100 %>
    
  </div>
  <div class="field">
    <%= f.label :file%><br />
    <%= f.file_field :image%>
  </div>
  
   <div class="actions">
    <%= f.submit "send mail" %>
  </div>
<% end %>

app/views/well/show.html.erb
<p>
<strong>TO:</strong>
<%= @message.to %>
</p>
<p>
<strong>From</strong>
<%= @message.user_id%>
</p>

<strong>MESSAGE</strong>
<%= @message.body.html_safe %>
<p>
<strong>FILE</strong>
<%= @message.image %></p>

app/views/well/trash.html.erb
<table>
  <tr>
    <!-- <th>TO</th> -->
    
    <th>MESSAGE</th>

    <th>FILE</th>
  </tr>
  
<% @message.each do |c| %>
<tr>
<td><%= c.to %></td>
<td><%#= c.trash %></td>
<td><%= c.body[0..10].html_safe %></td>
<td><%= c.image %></td>
<td><%= link_to"restore", well_restore_path(c) %></td>
<td><%= link_to"remove", well_remove_path(c) , method: :delete,data: { confirm: 'Are you sure?' }%></td>
<td><%#= link_to"view",well_path(c) %></td>
 <td><%#= link_to "delete",well_path(c) , method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>
</tr>
</table>
<%= link_to 'Back',  root_path %> 