config/routes.rb
Rails.application.routes.draw do

  get 'email/index'

  resources :profiles
  resources :contacts
get 'inbox'=> 'well#inbox'
get 'trash/well' => "well#trash" ,as: :tash_well
get 'well/restore/:id' => 'well#restore' ,as:  :well_restore
delete'well/deleted/:id' => 'well#delete', as: :well_remove
get 'favorite/well'=>"well#favorite_message" ,as: :favorite_well
get 'favorite_update'=> "well#favorite_update",as: :favorite_update
get 'home/index' => 'home#index' 
get '/new/home' => 'home#new'
put 'home/update'=>'home#update'

  resources :inbox
  resources :home

resources :well
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

   root 'email#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
 <meta charset="utf-8" />

 <!-- Uncomment to make IE8 render like IE7 -->
 <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

 <!-- Set the viewport width to device width for mobile -->
 <meta name="viewport" content="width=device-width, initial-scale=1.0" />

 <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

 <%= stylesheet_link_tag    "application" %>
 <%= javascript_include_tag "vendor/custom.modernizr" %>
 <script type="text/javascript" src="https://cdn.jsdelivr.net/jdenticon/1.3.2/jdenticon.min.js"></script>

 <%= csrf_meta_tags %>
</head>

</div>

<body>
  <div class="container-fluid">
    <div claass ="row">
      <div style="background-color:skyblue;padding:10px;">
        <nav class ="navbar navbar-defauld login-top">
          <div class="pull-right">
            <% if user_signed_in? %>
            <% if current_user.image_identifier.present? %>
            <%#=link_to image_tag(current_user.image_url.to_s, :height"40", :width"50"), edit_user_registration_path(current_user.id) %>
            <%else%>
            <canvas width="80" height="80" data-jdenticon-hash="<%= jdenticon %>"></canvas>
            
            <%end%>
            Signed in as <%= current_user.email %>. Not you?
            <%= current_user.username%>
            <%= link_to "compose",new_well_path %>
            <%= link_to "contact (#{@contuct_counts})",contacts_path %>
            <%= link_to "inbox (#{ @inbox_counts})",inbox_path %>
            <%= link_to "sendmail (#{@sendmail_counts })", well_index_path %>
            <%= link_to "favorite", favorite_well_path %>
            <%= link_to "trash",tash_well_path%>
            <%= link_to "calender",new_home_path %>
            
            <%= link_to "profile",edit_profile_path(id: current_user.id) %>

            <%#= image_tag (current_user.image_url.to_s,:class=> "img-circular" ) %>
            <%= link_to "logout", destroy_user_session_path, method: :delete %> |
            <%= link_to "edit", edit_user_registration_path %>
            

            <%else%>
            <%= link_to "Login", new_user_session_path %> |
            <%= link_to "Sign Up", new_user_registration_path %>
            <%end%>
          </div>
        </nav>
      </div>
    </div>
  </div>
  
  <%= yield %>
  
  
  <%= javascript_include_tag "application" %>
</body>
</html>